kind: pipeline
type: docker
name: go-test-ci

- name: go-test
  image: ubuntu-latest
  settings:
    username:
      from_secret: DOCKER_USER
    password:
      from_secret: DOCKER_PASSWORD
  commands:
  - go build
  - go test

